Models/Employee.cs
using System;
using System.Collections.Generic;

namespace WebRazor.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Accounts = new HashSet<Account>();
            Orders = new HashSet<Order>();
        }

        public int EmployeeId { get; set; }
        public string LastName { get; set; } = null!;
        public string FirstName { get; set; } = null!;
        public int? DepartmentId { get; set; }
        public string? Title { get; set; }
        public string? TitleOfCourtesy { get; set; }
        public DateTime? BirthDate { get; set; }
        public DateTime? HireDate { get; set; }
        public string? Address { get; set; }

        public virtual Department? Department { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}

Pages/Admin/Employee/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WebRazor.Materials;
using WebRazor.Models;

namespace WebRazor.Pages.Admin.Employee
{
    [Authorize(Roles = "Employee")]
    public class IndexModel : PageModel
    {
        private readonly PRN221DBContext dbContext;

        public IndexModel(PRN221DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [FromQuery(Name = "page")] public int Page { get; set; } = 1;
        private int perPage = 10;
        public List<Models.Employee> Employees { get; set; }
        [FromQuery(Name = "txtSearch")] public string Search { get; set; } = "";

        public List<String> PagesLink { get; set; } = new List<string>();

        public async Task<IActionResult> OnGetAsync()
        {

            await Load();

            return Page();
        }

        public async Task Load()
        {
            if (Search == null) Search = "";

            var query = dbContext.Employees;


            Employees = await query
                .OrderByDescending(p => p.EmployeeId)
                .Skip((Page - 1) * perPage).Take(perPage)
                .ToListAsync();

           /* PageLink page = new PageLink(perPage);
            PagesLink = page.getLink(Page, await query.CountAsync(), "/Admin/Employee/Index?");*/
        }

        public async Task<IActionResult> OnGetActive(int? id)
        {

            Models.Employee employee = await dbContext.Employees.FirstOrDefaultAsync(p => p.EmployeeId == id);
            if (employee != null)
            {
                /*employee.Active = !employee.Active;*/
                await dbContext.SaveChangesAsync();
            }

            return Redirect("/Admin/Employee/Index");
        }
    }
}

Pages/Admin/Employee/Index.cshtml
@page
@model WebRazor.Pages.Admin.Employee.IndexModel
@{
}
<div class="path-admin">EMPLOYEE LIST</div>

<div id="content-main-dashboard">
    <div id="product-title-header">
    </div>

    <div id="order-table-admin">
        <table id="orders">
            <tr>
                <th>EmployeeId</th>
                <th>Full Name</th>
                <th>Title</th>
                <th>Title Of Courtery</th>
                <th>Address</th>
                <th>Birth Date</th>
                <th>Hire Date</th>
                <th>Active</th>
            </tr>
            @foreach (var emp in Model.Employees)
            {
                <tr>
                    <td>#@emp.EmployeeId</td>
                    <td>@emp.FirstName @emp.LastName</td>
                    <td>@emp.Title</td>
                    <td>@emp.TitleOfCourtesy</td>
                    <td>@emp.Address</td>
                    <td>@((emp.BirthDate == null ? DateTime.Now : (DateTime)emp.BirthDate).ToString("dd/MM/yyyy"))</td>
                    <td>@((emp.HireDate == null ? DateTime.Now : (DateTime)emp.HireDate).ToString("dd/MM/yyyy"))</td>
                    <td>
                        @*<a class="delete" id="@emp.EmployeeId"
                       asp-page="/Admin/Employee/Index" asp-route-id="@emp.EmployeeId"
                       asp-page-handler="Active">@((bool)emp.Active ? "Active" : "Deactive")</a>*@
                    </td>
                </tr>
            }
        </table>
    </div>

    <div id="paging">
        <div class="pagination">
            @foreach (var item in Model.PagesLink)
            {
                @Html.Raw(item)
            }
        </div>
    </div>
</div>