Models/Order.cs
using System;
using System.Collections.Generic;

namespace WebRazor.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int OrderId { get; set; }
        public string? CustomerId { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public decimal? Freight { get; set; }
        public string? ShipName { get; set; }
        public string? ShipAddress { get; set; }
        public string? ShipCity { get; set; }
        public string? ShipRegion { get; set; }
        public string? ShipPostalCode { get; set; }
        public string? ShipCountry { get; set; }

        public virtual Customer? Customer { get; set; }
        public virtual Employee? Employee { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Pages/Admin/Order/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebRazor.Models;

namespace WebRazor.Pages.Admin.Order
{
    public class DetailModel : PageModel
    {
        public Models.Order Order { get; set;}
        public Models.OrderDetail OrderDetail { get; set;}

        private readonly PRN221DBContext dbContext;

        public int ID;

        public DetailModel(PRN221DBContext dbContext)
        {
            this.dbContext = dbContext;
        }


        public async Task<IActionResult> OnGet(int? id)
        {
            ID = (int)id;
            if(!dbContext.Orders.Select(order => order.OrderId).ToList().Contains(ID))
            {
                return NotFound();
            }

            Order = await dbContext.Orders
                .Include(o => o.OrderDetails)
                .FirstOrDefaultAsync(o => o.OrderId == id);

            OrderDetail = await dbContext.OrderDetails.Include(od => od.Product).FirstOrDefaultAsync(od => od.OrderId == id);

            return Page();
            /*foreach (var item in Order.OrderDetails)
            {
                item.Product = await dbContext.Products.Where(p => p.DeletedAt == null).FirstOrDefaultAsync(p => p.ProductId == item.ProductId);
            }*/
        }
    }
}

Pages/Admin/Order/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlTypes;
using System.Diagnostics;
using System.Linq;
using WebRazor.Materials;
using WebRazor.Models;

namespace WebRazor.Pages.Admin.Order
{
    public class IndexModel : PageModel
    {
        private readonly PRN221DBContext dbContext;
        [BindProperty] public List<Models.Order> Orders { get; set; }
        public List<String> PagesLink { get; set; } = new List<string>();

        [FromQuery(Name = "txtStartOrderDate")] public DateTime StartDate { get; set; }
        [FromQuery(Name = "txtEndOrderDate")] public DateTime EndDate { get; set; }

        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;
        public int Count;
        public int PageSize { get; set; } = 12;
        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));
        public bool IsShowPrevious => this.CurrentPage > 1;
        public bool IsShowNext => this.CurrentPage < this.TotalPages;

        public IndexModel(PRN221DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        private SqlDateTime? validateDateTime(DateTime time)
        {
            DateTime Min = (DateTime)SqlDateTime.MinValue;
            DateTime Max = (DateTime)SqlDateTime.MaxValue;
            

            if (time >= Min && time <= Max)
            {
                return SqlDateTime.Parse(time.Date.ToString("yyyy-MM-dd HH:mm:ss"));
            }

            return null;
        }

        public async Task LoadData(bool paging = true)
        {
            var queryRaw = dbContext.Orders
                .Where(q => true);

            SqlDateTime? sqlStartDate = validateDateTime(StartDate);
            SqlDateTime? sqlEndDate = validateDateTime(EndDate);


            if (sqlStartDate != null)
            {
                queryRaw = queryRaw.Where(q => (DateTime)q.OrderDate >= StartDate);
            }

            if (sqlEndDate != null)
            {
                queryRaw = queryRaw.Where(q => (DateTime)q.OrderDate <= EndDate);
            }

            var query = queryRaw;
            query = query.Include(q => q.Customer).Include(q => q.Employee)
                .OrderByDescending(o => o.OrderDate);

            if (paging)
                query = query.Skip((CurrentPage - 1) * PageSize).Take(PageSize);

            Orders = await query.ToListAsync();

            ViewData["StartDate"] = sqlStartDate != null ? StartDate.Date.ToString("yyyy-MM-dd") : "";
            ViewData["EndDate"] = sqlEndDate != null ? EndDate.Date.ToString("yyyy-MM-dd") : "";


        }


        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id != null)
            {
                CurrentPage = (int)id;
                SqlDateTime? sqlStartDate = validateDateTime(StartDate);
                SqlDateTime? sqlEndDate = validateDateTime(EndDate);
                if (sqlStartDate != null)
                {
                    Orders = dbContext.Orders.Where(o => (DateTime)o.OrderDate >= StartDate).ToList();
                } else if(sqlEndDate != null)
                {
                    Orders = dbContext.Orders.Where(o => (DateTime)o.OrderDate <= EndDate).ToList();
                } else
                {
                    Orders = dbContext.Orders.Include(p => p.Customer).Include(p => p.Employee).ToList();
                }
                Count = Orders.Count;
                Orders = GetPaginatedResult(CurrentPage, PageSize);
            }
            else
            {
                Orders = dbContext.Orders.Include(p => p.Customer).Include(p => p.Employee).ToList();
            }

            return Page();
        }

        public async Task<IActionResult> OnGetCancel(int? id, string target)
        {
            Models.Order order = await dbContext.Orders.FirstOrDefaultAsync(o => o.OrderId == id);

            await LoadData();

            if (order == null)
            {
                return Redirect(target);
            }
            order.RequiredDate = null;
            await dbContext.SaveChangesAsync();
            return Redirect(target);
        }

        public List<Models.Order> GetPaginatedResult(int currentPage, int pageSize)
        {
            return Orders.OrderBy(d => d.OrderId).Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();
        }
    }
}

Pages/Order/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text.Json;
using WebRazor.Models;

namespace WebRazor.Pages.Order
{
    public class AddModel : PageModel
    {
        private readonly PRN221DBContext dbContext;

        public AddModel(PRN221DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public Models.Account Auth { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (HttpContext.Session.GetString("Customer") == null)
            {
                return Redirect("/Account/Login");
            }

            Auth = JsonSerializer.Deserialize<Models.Account>(HttpContext.Session.GetString("Customer"));

            if (Auth == null)
            {
                return Redirect("/Account/Login");
            }
            Models.Product product = (await dbContext.Products.FirstOrDefaultAsync(p => p.ProductId == id));

            if (product == null || product.UnitsInStock == 0)
            {
                TempData["fail"] = "Quantity = 0";
            }
            else

                try
                {
                    Models.Order order = new Models.Order();
                    order.CustomerId = Auth.CustomerId;
                    order.OrderDate = DateTime.Now;
                    order.ShippedDate = DateTimeUtil.Add(DateTime.Now, TimeSpan.FromDays(7));
                    await dbContext.Orders.AddAsync(order);
                    await dbContext.SaveChangesAsync();
                    order = await dbContext.Orders.OrderBy(o => o.OrderDate).LastOrDefaultAsync();
                    OrderDetail od = new OrderDetail();
                    od.OrderId = order.OrderId;
                    od.ProductId = (int)id;
                    od.Quantity = 1;
                    od.UnitPrice = (decimal)product.UnitPrice;
                    od.Discount = 0;

                    await dbContext.OrderDetails.AddAsync(od);
                    await dbContext.SaveChangesAsync();

                    TempData["success"] = "Order successfull";
                }
                catch (Exception e)
                {
                    TempData["fail"] = e.Message;
                }

            return Redirect("/Product/Detail/" + id);
        }
    }
}

Pages/Order/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text.Json;
using WebRazor.Models;

namespace WebRazor.Pages.Order
{
    public class IndexModel : PageModel
    {
        private readonly PRN221DBContext dbContext;

        public IndexModel(PRN221DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public Models.Account Auth { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Models.Account acc = JsonSerializer.Deserialize<Models.Account>(HttpContext.Session.GetString("Account"));

            Auth = await dbContext.Accounts.FirstOrDefaultAsync(c => c.AccountId == acc.AccountId);
            var cus = await dbContext.Customers.ToListAsync();
            var ord = await dbContext.Orders.OrderByDescending(ord => ord.OrderDate).ToListAsync();
            var ordDe = await dbContext.OrderDetails.ToListAsync();
            var pro = await dbContext.Products.ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnGetAdd(int? id)
        {

            var check = HttpContext.User.FindFirst(ClaimTypes.Role);

            if (check != null && check.Value.Equals("Employee"))
            {
                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }

            Models.Product product = (await dbContext.Products.FirstOrDefaultAsync(p => p.ProductId == id));

            if (product == null || product.UnitsInStock == 0)
            {
                TempData["fail"] = "Quantity = 0";
                return Redirect("/Product/Detail/" + id);
            }
            else
            {
                Dictionary<int, int> list = getCart();

                if ((list.Where(p => p.Key == id)).Count() == 0)
                {
                    list.Add((int)id, 1);
                }


                HttpContext.Session.SetString("cart", JsonSerializer.Serialize(list));
                return Redirect("/Cart/Index");
            }
        }
        private Dictionary<int, int> getCart()
        {
            var cart = HttpContext.Session.GetString("cart");

            Dictionary<int, int> list;

            if (cart != null)
            {
                list = JsonSerializer.Deserialize<Dictionary<int, int>>(cart);
            }
            else
            {
                list = new Dictionary<int, int>();
            }

            return list;
        }


    }
}

Pages/Product/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebRazor.Models;

namespace WebRazor.Pages.Product
{
    public class DetailModel : PageModel
    {
        private readonly PRN221DBContext dbContext;

        public DetailModel(PRN221DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public Models.Product Product { get; set; }
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await dbContext.Products.FirstOrDefaultAsync(m => m.ProductId == id);
            var cat = await dbContext.Categories.ToListAsync();

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await dbContext.Products.FirstOrDefaultAsync(m => m.ProductId == id);
            var cat = await dbContext.Categories.ToListAsync();

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }


    }
}

Pages/Admin/Order/Detail.cshtml
@page "{id:int?}"
@model WebRazor.Pages.Admin.Order.DetailModel
@{
    int getStatus(DateTime? requiredDate, DateTime? shippedDate, int orderId)
    {
        if (shippedDate != null)
        {
            return 1;
        }

        if (requiredDate != null)
        {
            return 2;
        }

        return 3;
    }
}
<div id="content-main-dashboard">
    <div>
        <div class="profile-order-title">
            <div class="profile-order-title-left">
                <div>OrderID: #@Model.Order.OrderId</div>
                <div>Order creation date: @(((DateTime)Model.Order.OrderDate).ToString("dd-MM-yyyy"))</div>
            </div>
            <div class="profile-order-title-right">

                @{
                    int status = getStatus(Model.Order.RequiredDate, Model.Order.ShippedDate, Model.Order.OrderId);
                    switch (status)
                    {
                        case 1:
                            <span style="color: green;">Completed</span>
                            break;
                        case 2:
                            <span style="color: blue;">
                                Pending | <a asp-page="/Admin/Order/Index"
                                 asp-route-target="/Admin/Order/Detail/@Model.ID"
                                 asp-page-handler="Cancel" asp-route-id="@Model.Order.OrderId">Cancel</a>
                            </span>
                            break;
                        default:
                            <span style='color: red;'>Order canceled</span>
                            break;
                    }
                }
            </div>
        </div>
        @foreach (var item in Model.Order.OrderDetails)
        {
            <div class="profile-order-content" style="background-color: white;">
                <div class="profile-order-content-col1">
                    <a href="detail.html"><img src="~/img/2.jpg" width="100%" /></a>
                </div>
                <div class="profile-order-content-col2">@item.Product.ProductName</div>
                <div class="profile-order-content-col3">Quantity: @item.Quantity</div>
                <div class="profile-order-content-col4">@(((float)item.UnitPrice * item.Quantity * (1 - item.Discount)).ToString("G29")) $</div>
            </div>
        }

    </div>
</div>

Pages/Admin/Order/Index.cshtml
@page "{id:int?}"
@model WebRazor.Pages.Admin.Order.IndexModel
@{
    string format(DateTime? date){
        if (date == null)
            return "";
        return ((DateTime)date).Date.ToString("dd-MM-yyyy");
    }

    int getStatus(DateTime? requiredDate, DateTime? shippedDate, int orderId)
    {
        if(shippedDate != null){
            return 1;
        }

        if(requiredDate != null){
            return 2;
        }

        return 3;
    }
}
<div id="content-main-dashboard">
    <div id="order-title">
        <b>Filter by Order date:</b>
        <form>
            From: <input type="date" name="txtStartOrderDate" value="@ViewData["StartDate"]" />
            To: <input type="date" name="txtEndOrderDate" value="@ViewData["EndDate"]" />
            <input type="submit" value="Filter">
        </form>
    </div>

    <div id="order-table">
        <table id="orders">
            <tr>
                <th>OrderID</th>
                <th>OrderDate</th>
                <th>RequiredDate</th>
                <th>ShippedDate</th>
                <th>Employee</th>
                <th>Customer</th>
                <th>Freight($)</th>
                <th>Status</th>
            </tr>
            @foreach(var item in Model.Orders){
                <tr>
                    <td><a asp-page="/Admin/Order/Detail" asp-route-id="@item.OrderId">#@item.OrderId</a></td>
                    <td>@format(item.OrderDate)</td>
                    <td>@format(item.RequiredDate)</td>
                    <td>@format(item.ShippedDate)</td>
                    <td>@(item.Employee != null ? (item.Employee.FirstName+ " " +item.Employee.LastName) : "")</td>
                    <td>@(item.Customer != null ? item.Customer.ContactName : "")</td>
                    <td>@(((decimal)item.Freight).ToString("G29")) </td>
                    @{
                        int status = getStatus(item.RequiredDate, item.ShippedDate, item.OrderId);
                        switch (status)
                        {
                            case 1:
                                        <td style="color: green;">Completed</td>
                                break; 
                            case 2:
                                        <td style="color: blue;">Pending | <a asp-page="/Admin/Order/Index"
                                 asp-route-target="/Admin/Order/Index"
                                 asp-page-handler="Cancel" asp-route-id="@item.OrderId">Cancel</a>
                                        </td>
                                break;
                            default:
                                        <td style='color: red;'>Order canceled</td>
                                break;
                        }
                    }
                </tr>
            }
        </table>
    </div>
    <div id="paging">
        <div class="pagination">
            @if (Model.IsShowPrevious)
            {
                <a href="~/admin/order/@(@Model.CurrentPage-1)">&laquo;</a>
            }
            @for (var i = 1; i <= Model.TotalPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                    <a style="background-color:orange" href="~/admin/order/@i">@i</a>
                }
                else
                {
                    <a href="~/admin/order/@i">@i</a>

                }
            }
            @if (Model.IsShowNext)
            {
                <a href="~/admin/order/@(@Model.CurrentPage+1)">&raquo;</a>
            }
        </div>
    </div>
</div>